version: '3'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: caloriesmanager
    networks:
      my_network:
        ipv4_address: 192.168.1.100

  calories-app:
    build: .
    restart: always
    ports:
      - "8888:8080"
    networks:
      my_network:
        ipv4_address: 192.168.1.101

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - "5555:8080"
    networks:
      my_network:
        ipv4_address: 192.168.1.102


networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24