version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: caloriesmanager
    networks:
      my_network:
        ipv4_address: 192.168.1.100

  calories-app:
    build: .
    ports:
      - "8888:8080"
    networks:
      my_network:
        ipv4_address: 192.168.1.101

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24